namespace SuperMarioBros.Utils.DataStructures
{
    public enum EntitiesName
    {
        GOOMBA,
        KOOPA,
        POLE,
        BLOCK,
        COIN,
        MUSHROOM,
        STAR,
        FLOWER,
        PIPE,
        FLAG,
        FLAGBALL,
        POWERUP,
        NORMAL,
        CASTLE,
        MARIO,
        BIGMARIO,
        FIREMARIO,
        QUESTIONBLOCK,
        COINBLOCK,
        DUCT,
        DUCTEXTENSION,
        BLOCKERBLOCKBROWN,
        DUCTCROSS,
        SECRETLEVELDUCTENTRANCE,
        FIRE,
        FIREEXPLOSION
    }
}
