name: CI

on:
    pull_request:
        branches:
            - 'develop'
        types: [opened]
        paths:
            - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Roslyn Analyzers
      run: dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

    - name: Run Roslyn Analyzers
      run: dotnet build --no-restore /p:RunAnalyzersDuringBuild=true /p:TreatWarningsAsErrors=true


  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Install dotnet format tool
      run: dotnet tool install -g dotnet-format

    - name: Add dotnet tools to PATH
      run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

    - name: Run dotnet format
      run: dotnet format --verify-no-changes
